name: base
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - matplotlib
  - scipy
  - ipykernel
  - ipywidgets
  - ipyfilechooser
  - ipylab
  - voila
  - jupytext
  - jupyter_http_over_ws
  - jupyter-resource-usage
  - jupyterlab-system-monitor
  - jupyterlab-git
  - nb_conda_kernels
  - python-dotenv
  - tqdm
  - jupyter-server-proxy
  - pillow
  - qrcode
  - pip:
    - pyodm==1.5.9
    - rasterio
    - rasterstats
    - GEOS
    - cartopy
    - opencv-contrib-python-headless
    - gdal==GDAL_VERSION
    - git+https://github.com/AuScalableDroneCloud/asdc_python
    - git+https://github.com/AuScalableDroneCloud/nbgitpuller
    - git+https://github.com/AuScalableDroneCloud/odk2odm
    - git+https://github.com/AuScalableDroneCloud/odmax
