name: base
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - nb_conda_kernels
  - pip:
    - ipywidgets
    - ipyfilechooser
    - ipylab
    - jupytext
    - jupyter_http_over_ws
    - jupyter-resource-usage
    - jupyterlab-system-monitor
    - jupyterlab-git
    - python-dotenv
    - jupyter-server-proxy
    - git+https://github.com/AuScalableDroneCloud/asdc_python